// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestApi.Models
{
    public partial class Registration
    {
        public int Id { get; set; }
        public int? InitialCode { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string JoinStatus { get; set; }
        public int? ProjectCode { get; set; }
    }
}